# Generated by Django 4.1.2 on 2022-10-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="is_active",
            field=models.CharField(max_length=120),
        ),
    ]
