# Generated by Django 4.1.2 on 2022-10-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0003_alter_categories_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="is_active",
            field=models.BooleanField(default=True, max_length=120),
        ),
    ]
